import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google"


export const metadata: Metadata = {
  title: "Lux-Sole",
  description: "Generated by create next app",
};

export const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
