import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Lux-Sole",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="overflow-x-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}